// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.magaldima.aw.apis;

public interface AssetIdentifierOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aw.apis.AssetIdentifier)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string kind = 1;</code>
   */
  java.lang.String getKind();
  /**
   * <code>string kind = 1;</code>
   */
  com.google.protobuf.ByteString
      getKindBytes();

  /**
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
