// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.magaldima.aw.apis;

public interface CreatePortfolioRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aw.apis.CreatePortfolioRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.aw.apis.Portfolio portfolio = 1;</code>
   */
  boolean hasPortfolio();
  /**
   * <code>.aw.apis.Portfolio portfolio = 1;</code>
   */
  io.magaldima.aw.apis.Portfolio getPortfolio();
  /**
   * <code>.aw.apis.Portfolio portfolio = 1;</code>
   */
  io.magaldima.aw.apis.PortfolioOrBuilder getPortfolioOrBuilder();
}
