// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.magaldima.aw.apis;

public final class PortfoliosProto {
  private PortfoliosProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aw_apis_GetPortfolioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aw_apis_GetPortfolioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aw_apis_CreatePortfolioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aw_apis_CreatePortfolioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aw_apis_DeletePortfolioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aw_apis_DeletePortfolioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aw_apis_Portfolio_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aw_apis_Portfolio_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aw_apis_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aw_apis_Position_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aw_apis_AssetIdentifier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aw_apis_AssetIdentifier_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017portfolio.proto\022\007aw.apis\032\033google/proto" +
      "buf/empty.proto\032\034google/api/annotations." +
      "proto\"1\n\023GetPortfolioRequest\022\n\n\002id\030\001 \001(\t" +
      "\022\016\n\006tenant\030\002 \001(\t\"?\n\026CreatePortfolioReque" +
      "st\022%\n\tportfolio\030\001 \001(\0132\022.aw.apis.Portfoli" +
      "o\"4\n\026DeletePortfolioRequest\022\n\n\002id\030\001 \001(\t\022" +
      "\016\n\006tenant\030\002 \001(\t\"O\n\tPortfolio\022\n\n\002id\030\001 \001(\t" +
      "\022\020\n\010currency\030\002 \001(\t\022$\n\tpositions\030\003 \003(\0132\021." +
      "aw.apis.Position\"}\n\010Position\022\n\n\002id\030\001 \001(\t" +
      "\022\017\n\007assetId\030\002 \001(\t\022-\n\013identifiers\030\003 \003(\0132\030" +
      ".aw.apis.AssetIdentifier\022\023\n\013marketValue\030" +
      "\004 \001(\001\022\020\n\010quantity\030\005 \001(\001\".\n\017AssetIdentifi" +
      "er\022\014\n\004kind\030\001 \001(\t\022\r\n\005value\030\002 \001(\t2\225\002\n\020Port" +
      "folioService\022T\n\003Get\022\034.aw.apis.GetPortfol" +
      "ioRequest\032\022.aw.apis.Portfolio\"\033\202\323\344\223\002\025\022\023/" +
      "v1/portfolios/{id}\022K\n\006Create\022\022.aw.apis.P" +
      "ortfolio\032\022.aw.apis.Portfolio\"\031\202\323\344\223\002\023\"\016/v" +
      "1/portfolios:\001*\022^\n\006Delete\022\037.aw.apis.Dele" +
      "tePortfolioRequest\032\026.google.protobuf.Emp" +
      "ty\"\033\202\323\344\223\002\025*\023/v1/portfolios/{id}B)\n\024io.ma" +
      "galdima.aw.apisB\017PortfoliosProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_aw_apis_GetPortfolioRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aw_apis_GetPortfolioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aw_apis_GetPortfolioRequest_descriptor,
        new java.lang.String[] { "Id", "Tenant", });
    internal_static_aw_apis_CreatePortfolioRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aw_apis_CreatePortfolioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aw_apis_CreatePortfolioRequest_descriptor,
        new java.lang.String[] { "Portfolio", });
    internal_static_aw_apis_DeletePortfolioRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_aw_apis_DeletePortfolioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aw_apis_DeletePortfolioRequest_descriptor,
        new java.lang.String[] { "Id", "Tenant", });
    internal_static_aw_apis_Portfolio_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_aw_apis_Portfolio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aw_apis_Portfolio_descriptor,
        new java.lang.String[] { "Id", "Currency", "Positions", });
    internal_static_aw_apis_Position_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_aw_apis_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aw_apis_Position_descriptor,
        new java.lang.String[] { "Id", "AssetId", "Identifiers", "MarketValue", "Quantity", });
    internal_static_aw_apis_AssetIdentifier_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_aw_apis_AssetIdentifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aw_apis_AssetIdentifier_descriptor,
        new java.lang.String[] { "Kind", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
