// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.magaldima.aw.apis;

public interface PositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aw.apis.Position)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string assetId = 2;</code>
   */
  java.lang.String getAssetId();
  /**
   * <code>string assetId = 2;</code>
   */
  com.google.protobuf.ByteString
      getAssetIdBytes();

  /**
   * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
   */
  java.util.List<io.magaldima.aw.apis.AssetIdentifier> 
      getIdentifiersList();
  /**
   * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
   */
  io.magaldima.aw.apis.AssetIdentifier getIdentifiers(int index);
  /**
   * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
   */
  int getIdentifiersCount();
  /**
   * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
   */
  java.util.List<? extends io.magaldima.aw.apis.AssetIdentifierOrBuilder> 
      getIdentifiersOrBuilderList();
  /**
   * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
   */
  io.magaldima.aw.apis.AssetIdentifierOrBuilder getIdentifiersOrBuilder(
      int index);

  /**
   * <code>double marketValue = 4;</code>
   */
  double getMarketValue();

  /**
   * <code>double quantity = 5;</code>
   */
  double getQuantity();
}
