// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.magaldima.aw.apis;

/**
 * Protobuf type {@code aw.apis.Position}
 */
public  final class Position extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aw.apis.Position)
    PositionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Position.newBuilder() to construct.
  private Position(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Position() {
    id_ = "";
    assetId_ = "";
    identifiers_ = java.util.Collections.emptyList();
    marketValue_ = 0D;
    quantity_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Position(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            assetId_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              identifiers_ = new java.util.ArrayList<io.magaldima.aw.apis.AssetIdentifier>();
              mutable_bitField0_ |= 0x00000004;
            }
            identifiers_.add(
                input.readMessage(io.magaldima.aw.apis.AssetIdentifier.parser(), extensionRegistry));
            break;
          }
          case 33: {

            marketValue_ = input.readDouble();
            break;
          }
          case 41: {

            quantity_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        identifiers_ = java.util.Collections.unmodifiableList(identifiers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.magaldima.aw.apis.PortfoliosProto.internal_static_aw_apis_Position_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.magaldima.aw.apis.PortfoliosProto.internal_static_aw_apis_Position_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.magaldima.aw.apis.Position.class, io.magaldima.aw.apis.Position.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSETID_FIELD_NUMBER = 2;
  private volatile java.lang.Object assetId_;
  /**
   * <code>string assetId = 2;</code>
   */
  public java.lang.String getAssetId() {
    java.lang.Object ref = assetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assetId_ = s;
      return s;
    }
  }
  /**
   * <code>string assetId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAssetIdBytes() {
    java.lang.Object ref = assetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDENTIFIERS_FIELD_NUMBER = 3;
  private java.util.List<io.magaldima.aw.apis.AssetIdentifier> identifiers_;
  /**
   * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
   */
  public java.util.List<io.magaldima.aw.apis.AssetIdentifier> getIdentifiersList() {
    return identifiers_;
  }
  /**
   * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
   */
  public java.util.List<? extends io.magaldima.aw.apis.AssetIdentifierOrBuilder> 
      getIdentifiersOrBuilderList() {
    return identifiers_;
  }
  /**
   * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
   */
  public int getIdentifiersCount() {
    return identifiers_.size();
  }
  /**
   * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
   */
  public io.magaldima.aw.apis.AssetIdentifier getIdentifiers(int index) {
    return identifiers_.get(index);
  }
  /**
   * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
   */
  public io.magaldima.aw.apis.AssetIdentifierOrBuilder getIdentifiersOrBuilder(
      int index) {
    return identifiers_.get(index);
  }

  public static final int MARKETVALUE_FIELD_NUMBER = 4;
  private double marketValue_;
  /**
   * <code>double marketValue = 4;</code>
   */
  public double getMarketValue() {
    return marketValue_;
  }

  public static final int QUANTITY_FIELD_NUMBER = 5;
  private double quantity_;
  /**
   * <code>double quantity = 5;</code>
   */
  public double getQuantity() {
    return quantity_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getAssetIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, assetId_);
    }
    for (int i = 0; i < identifiers_.size(); i++) {
      output.writeMessage(3, identifiers_.get(i));
    }
    if (marketValue_ != 0D) {
      output.writeDouble(4, marketValue_);
    }
    if (quantity_ != 0D) {
      output.writeDouble(5, quantity_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getAssetIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, assetId_);
    }
    for (int i = 0; i < identifiers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, identifiers_.get(i));
    }
    if (marketValue_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, marketValue_);
    }
    if (quantity_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, quantity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.magaldima.aw.apis.Position)) {
      return super.equals(obj);
    }
    io.magaldima.aw.apis.Position other = (io.magaldima.aw.apis.Position) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getAssetId()
        .equals(other.getAssetId());
    result = result && getIdentifiersList()
        .equals(other.getIdentifiersList());
    result = result && (
        java.lang.Double.doubleToLongBits(getMarketValue())
        == java.lang.Double.doubleToLongBits(
            other.getMarketValue()));
    result = result && (
        java.lang.Double.doubleToLongBits(getQuantity())
        == java.lang.Double.doubleToLongBits(
            other.getQuantity()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + ASSETID_FIELD_NUMBER;
    hash = (53 * hash) + getAssetId().hashCode();
    if (getIdentifiersCount() > 0) {
      hash = (37 * hash) + IDENTIFIERS_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifiersList().hashCode();
    }
    hash = (37 * hash) + MARKETVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMarketValue()));
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getQuantity()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.magaldima.aw.apis.Position parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.magaldima.aw.apis.Position parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.magaldima.aw.apis.Position parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.magaldima.aw.apis.Position parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.magaldima.aw.apis.Position parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.magaldima.aw.apis.Position parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.magaldima.aw.apis.Position parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.magaldima.aw.apis.Position parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.magaldima.aw.apis.Position parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.magaldima.aw.apis.Position parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.magaldima.aw.apis.Position parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.magaldima.aw.apis.Position parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.magaldima.aw.apis.Position prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code aw.apis.Position}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aw.apis.Position)
      io.magaldima.aw.apis.PositionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.magaldima.aw.apis.PortfoliosProto.internal_static_aw_apis_Position_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.magaldima.aw.apis.PortfoliosProto.internal_static_aw_apis_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.magaldima.aw.apis.Position.class, io.magaldima.aw.apis.Position.Builder.class);
    }

    // Construct using io.magaldima.aw.apis.Position.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIdentifiersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      assetId_ = "";

      if (identifiersBuilder_ == null) {
        identifiers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        identifiersBuilder_.clear();
      }
      marketValue_ = 0D;

      quantity_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.magaldima.aw.apis.PortfoliosProto.internal_static_aw_apis_Position_descriptor;
    }

    public io.magaldima.aw.apis.Position getDefaultInstanceForType() {
      return io.magaldima.aw.apis.Position.getDefaultInstance();
    }

    public io.magaldima.aw.apis.Position build() {
      io.magaldima.aw.apis.Position result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.magaldima.aw.apis.Position buildPartial() {
      io.magaldima.aw.apis.Position result = new io.magaldima.aw.apis.Position(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.assetId_ = assetId_;
      if (identifiersBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          identifiers_ = java.util.Collections.unmodifiableList(identifiers_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.identifiers_ = identifiers_;
      } else {
        result.identifiers_ = identifiersBuilder_.build();
      }
      result.marketValue_ = marketValue_;
      result.quantity_ = quantity_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.magaldima.aw.apis.Position) {
        return mergeFrom((io.magaldima.aw.apis.Position)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.magaldima.aw.apis.Position other) {
      if (other == io.magaldima.aw.apis.Position.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getAssetId().isEmpty()) {
        assetId_ = other.assetId_;
        onChanged();
      }
      if (identifiersBuilder_ == null) {
        if (!other.identifiers_.isEmpty()) {
          if (identifiers_.isEmpty()) {
            identifiers_ = other.identifiers_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureIdentifiersIsMutable();
            identifiers_.addAll(other.identifiers_);
          }
          onChanged();
        }
      } else {
        if (!other.identifiers_.isEmpty()) {
          if (identifiersBuilder_.isEmpty()) {
            identifiersBuilder_.dispose();
            identifiersBuilder_ = null;
            identifiers_ = other.identifiers_;
            bitField0_ = (bitField0_ & ~0x00000004);
            identifiersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIdentifiersFieldBuilder() : null;
          } else {
            identifiersBuilder_.addAllMessages(other.identifiers_);
          }
        }
      }
      if (other.getMarketValue() != 0D) {
        setMarketValue(other.getMarketValue());
      }
      if (other.getQuantity() != 0D) {
        setQuantity(other.getQuantity());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.magaldima.aw.apis.Position parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.magaldima.aw.apis.Position) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assetId_ = "";
    /**
     * <code>string assetId = 2;</code>
     */
    public java.lang.String getAssetId() {
      java.lang.Object ref = assetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string assetId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAssetIdBytes() {
      java.lang.Object ref = assetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string assetId = 2;</code>
     */
    public Builder setAssetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string assetId = 2;</code>
     */
    public Builder clearAssetId() {
      
      assetId_ = getDefaultInstance().getAssetId();
      onChanged();
      return this;
    }
    /**
     * <code>string assetId = 2;</code>
     */
    public Builder setAssetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assetId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<io.magaldima.aw.apis.AssetIdentifier> identifiers_ =
      java.util.Collections.emptyList();
    private void ensureIdentifiersIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        identifiers_ = new java.util.ArrayList<io.magaldima.aw.apis.AssetIdentifier>(identifiers_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.magaldima.aw.apis.AssetIdentifier, io.magaldima.aw.apis.AssetIdentifier.Builder, io.magaldima.aw.apis.AssetIdentifierOrBuilder> identifiersBuilder_;

    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public java.util.List<io.magaldima.aw.apis.AssetIdentifier> getIdentifiersList() {
      if (identifiersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(identifiers_);
      } else {
        return identifiersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public int getIdentifiersCount() {
      if (identifiersBuilder_ == null) {
        return identifiers_.size();
      } else {
        return identifiersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public io.magaldima.aw.apis.AssetIdentifier getIdentifiers(int index) {
      if (identifiersBuilder_ == null) {
        return identifiers_.get(index);
      } else {
        return identifiersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public Builder setIdentifiers(
        int index, io.magaldima.aw.apis.AssetIdentifier value) {
      if (identifiersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdentifiersIsMutable();
        identifiers_.set(index, value);
        onChanged();
      } else {
        identifiersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public Builder setIdentifiers(
        int index, io.magaldima.aw.apis.AssetIdentifier.Builder builderForValue) {
      if (identifiersBuilder_ == null) {
        ensureIdentifiersIsMutable();
        identifiers_.set(index, builderForValue.build());
        onChanged();
      } else {
        identifiersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public Builder addIdentifiers(io.magaldima.aw.apis.AssetIdentifier value) {
      if (identifiersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdentifiersIsMutable();
        identifiers_.add(value);
        onChanged();
      } else {
        identifiersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public Builder addIdentifiers(
        int index, io.magaldima.aw.apis.AssetIdentifier value) {
      if (identifiersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdentifiersIsMutable();
        identifiers_.add(index, value);
        onChanged();
      } else {
        identifiersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public Builder addIdentifiers(
        io.magaldima.aw.apis.AssetIdentifier.Builder builderForValue) {
      if (identifiersBuilder_ == null) {
        ensureIdentifiersIsMutable();
        identifiers_.add(builderForValue.build());
        onChanged();
      } else {
        identifiersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public Builder addIdentifiers(
        int index, io.magaldima.aw.apis.AssetIdentifier.Builder builderForValue) {
      if (identifiersBuilder_ == null) {
        ensureIdentifiersIsMutable();
        identifiers_.add(index, builderForValue.build());
        onChanged();
      } else {
        identifiersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public Builder addAllIdentifiers(
        java.lang.Iterable<? extends io.magaldima.aw.apis.AssetIdentifier> values) {
      if (identifiersBuilder_ == null) {
        ensureIdentifiersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, identifiers_);
        onChanged();
      } else {
        identifiersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public Builder clearIdentifiers() {
      if (identifiersBuilder_ == null) {
        identifiers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        identifiersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public Builder removeIdentifiers(int index) {
      if (identifiersBuilder_ == null) {
        ensureIdentifiersIsMutable();
        identifiers_.remove(index);
        onChanged();
      } else {
        identifiersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public io.magaldima.aw.apis.AssetIdentifier.Builder getIdentifiersBuilder(
        int index) {
      return getIdentifiersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public io.magaldima.aw.apis.AssetIdentifierOrBuilder getIdentifiersOrBuilder(
        int index) {
      if (identifiersBuilder_ == null) {
        return identifiers_.get(index);  } else {
        return identifiersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public java.util.List<? extends io.magaldima.aw.apis.AssetIdentifierOrBuilder> 
         getIdentifiersOrBuilderList() {
      if (identifiersBuilder_ != null) {
        return identifiersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(identifiers_);
      }
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public io.magaldima.aw.apis.AssetIdentifier.Builder addIdentifiersBuilder() {
      return getIdentifiersFieldBuilder().addBuilder(
          io.magaldima.aw.apis.AssetIdentifier.getDefaultInstance());
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public io.magaldima.aw.apis.AssetIdentifier.Builder addIdentifiersBuilder(
        int index) {
      return getIdentifiersFieldBuilder().addBuilder(
          index, io.magaldima.aw.apis.AssetIdentifier.getDefaultInstance());
    }
    /**
     * <code>repeated .aw.apis.AssetIdentifier identifiers = 3;</code>
     */
    public java.util.List<io.magaldima.aw.apis.AssetIdentifier.Builder> 
         getIdentifiersBuilderList() {
      return getIdentifiersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.magaldima.aw.apis.AssetIdentifier, io.magaldima.aw.apis.AssetIdentifier.Builder, io.magaldima.aw.apis.AssetIdentifierOrBuilder> 
        getIdentifiersFieldBuilder() {
      if (identifiersBuilder_ == null) {
        identifiersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.magaldima.aw.apis.AssetIdentifier, io.magaldima.aw.apis.AssetIdentifier.Builder, io.magaldima.aw.apis.AssetIdentifierOrBuilder>(
                identifiers_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        identifiers_ = null;
      }
      return identifiersBuilder_;
    }

    private double marketValue_ ;
    /**
     * <code>double marketValue = 4;</code>
     */
    public double getMarketValue() {
      return marketValue_;
    }
    /**
     * <code>double marketValue = 4;</code>
     */
    public Builder setMarketValue(double value) {
      
      marketValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double marketValue = 4;</code>
     */
    public Builder clearMarketValue() {
      
      marketValue_ = 0D;
      onChanged();
      return this;
    }

    private double quantity_ ;
    /**
     * <code>double quantity = 5;</code>
     */
    public double getQuantity() {
      return quantity_;
    }
    /**
     * <code>double quantity = 5;</code>
     */
    public Builder setQuantity(double value) {
      
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double quantity = 5;</code>
     */
    public Builder clearQuantity() {
      
      quantity_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aw.apis.Position)
  }

  // @@protoc_insertion_point(class_scope:aw.apis.Position)
  private static final io.magaldima.aw.apis.Position DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.magaldima.aw.apis.Position();
  }

  public static io.magaldima.aw.apis.Position getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Position>
      PARSER = new com.google.protobuf.AbstractParser<Position>() {
    public Position parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Position(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Position> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Position> getParserForType() {
    return PARSER;
  }

  public io.magaldima.aw.apis.Position getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

