// Code generated by protoc-gen-go. DO NOT EDIT.
// source: portfolio.proto

package aw_apis

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPortfolioRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortfolioRequest) Reset()         { *m = GetPortfolioRequest{} }
func (m *GetPortfolioRequest) String() string { return proto.CompactTextString(m) }
func (*GetPortfolioRequest) ProtoMessage()    {}
func (*GetPortfolioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{0}
}

func (m *GetPortfolioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortfolioRequest.Unmarshal(m, b)
}
func (m *GetPortfolioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortfolioRequest.Marshal(b, m, deterministic)
}
func (m *GetPortfolioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortfolioRequest.Merge(m, src)
}
func (m *GetPortfolioRequest) XXX_Size() int {
	return xxx_messageInfo_GetPortfolioRequest.Size(m)
}
func (m *GetPortfolioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortfolioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortfolioRequest proto.InternalMessageInfo

func (m *GetPortfolioRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetPortfolioRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type CreatePortfolioRequest struct {
	Portfolio            *Portfolio `protobuf:"bytes,1,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreatePortfolioRequest) Reset()         { *m = CreatePortfolioRequest{} }
func (m *CreatePortfolioRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePortfolioRequest) ProtoMessage()    {}
func (*CreatePortfolioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{1}
}

func (m *CreatePortfolioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePortfolioRequest.Unmarshal(m, b)
}
func (m *CreatePortfolioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePortfolioRequest.Marshal(b, m, deterministic)
}
func (m *CreatePortfolioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePortfolioRequest.Merge(m, src)
}
func (m *CreatePortfolioRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePortfolioRequest.Size(m)
}
func (m *CreatePortfolioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePortfolioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePortfolioRequest proto.InternalMessageInfo

func (m *CreatePortfolioRequest) GetPortfolio() *Portfolio {
	if m != nil {
		return m.Portfolio
	}
	return nil
}

type DeletePortfolioRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePortfolioRequest) Reset()         { *m = DeletePortfolioRequest{} }
func (m *DeletePortfolioRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePortfolioRequest) ProtoMessage()    {}
func (*DeletePortfolioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{2}
}

func (m *DeletePortfolioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePortfolioRequest.Unmarshal(m, b)
}
func (m *DeletePortfolioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePortfolioRequest.Marshal(b, m, deterministic)
}
func (m *DeletePortfolioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePortfolioRequest.Merge(m, src)
}
func (m *DeletePortfolioRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePortfolioRequest.Size(m)
}
func (m *DeletePortfolioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePortfolioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePortfolioRequest proto.InternalMessageInfo

func (m *DeletePortfolioRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeletePortfolioRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type Portfolio struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Currency             string      `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Positions            []*Position `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Portfolio) Reset()         { *m = Portfolio{} }
func (m *Portfolio) String() string { return proto.CompactTextString(m) }
func (*Portfolio) ProtoMessage()    {}
func (*Portfolio) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{3}
}

func (m *Portfolio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portfolio.Unmarshal(m, b)
}
func (m *Portfolio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portfolio.Marshal(b, m, deterministic)
}
func (m *Portfolio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portfolio.Merge(m, src)
}
func (m *Portfolio) XXX_Size() int {
	return xxx_messageInfo_Portfolio.Size(m)
}
func (m *Portfolio) XXX_DiscardUnknown() {
	xxx_messageInfo_Portfolio.DiscardUnknown(m)
}

var xxx_messageInfo_Portfolio proto.InternalMessageInfo

func (m *Portfolio) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Portfolio) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Portfolio) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

type Position struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetId              string             `protobuf:"bytes,2,opt,name=assetId,proto3" json:"assetId,omitempty"`
	Identifiers          []*AssetIdentifier `protobuf:"bytes,3,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	MarketValue          float64            `protobuf:"fixed64,4,opt,name=marketValue,proto3" json:"marketValue,omitempty"`
	Quantity             float64            `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{4}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Position) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *Position) GetIdentifiers() []*AssetIdentifier {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *Position) GetMarketValue() float64 {
	if m != nil {
		return m.MarketValue
	}
	return 0
}

func (m *Position) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type AssetIdentifier struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetIdentifier) Reset()         { *m = AssetIdentifier{} }
func (m *AssetIdentifier) String() string { return proto.CompactTextString(m) }
func (*AssetIdentifier) ProtoMessage()    {}
func (*AssetIdentifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_c193a9c2ca89d2ee, []int{5}
}

func (m *AssetIdentifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetIdentifier.Unmarshal(m, b)
}
func (m *AssetIdentifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetIdentifier.Marshal(b, m, deterministic)
}
func (m *AssetIdentifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetIdentifier.Merge(m, src)
}
func (m *AssetIdentifier) XXX_Size() int {
	return xxx_messageInfo_AssetIdentifier.Size(m)
}
func (m *AssetIdentifier) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetIdentifier.DiscardUnknown(m)
}

var xxx_messageInfo_AssetIdentifier proto.InternalMessageInfo

func (m *AssetIdentifier) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *AssetIdentifier) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPortfolioRequest)(nil), "aw.apis.GetPortfolioRequest")
	proto.RegisterType((*CreatePortfolioRequest)(nil), "aw.apis.CreatePortfolioRequest")
	proto.RegisterType((*DeletePortfolioRequest)(nil), "aw.apis.DeletePortfolioRequest")
	proto.RegisterType((*Portfolio)(nil), "aw.apis.Portfolio")
	proto.RegisterType((*Position)(nil), "aw.apis.Position")
	proto.RegisterType((*AssetIdentifier)(nil), "aw.apis.AssetIdentifier")
}

func init() { proto.RegisterFile("portfolio.proto", fileDescriptor_c193a9c2ca89d2ee) }

var fileDescriptor_c193a9c2ca89d2ee = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0xa7, 0x4d, 0x9b, 0x89, 0xd4, 0xc0, 0xa4, 0x44, 0xc6, 0xad, 0x44, 0xe4, 0x53,
	0xe8, 0xc1, 0x86, 0x70, 0x2b, 0x42, 0x82, 0x02, 0xaa, 0x80, 0x4b, 0x64, 0x10, 0x47, 0xa4, 0x6d,
	0x3c, 0x09, 0xab, 0x3a, 0x5e, 0xd7, 0x5e, 0x07, 0x45, 0x88, 0x0b, 0xaf, 0x80, 0x78, 0x0d, 0x5e,
	0x86, 0x57, 0xe0, 0x41, 0x50, 0x76, 0xbd, 0x9b, 0x40, 0x7c, 0xe8, 0xcd, 0x33, 0xf3, 0xcf, 0x37,
	0xbf, 0x77, 0x67, 0xa1, 0x97, 0x8b, 0x42, 0xce, 0x44, 0xca, 0x45, 0x98, 0x17, 0x42, 0x0a, 0x3c,
	0x60, 0x5f, 0x42, 0x96, 0xf3, 0xd2, 0x3f, 0x99, 0x0b, 0x31, 0x4f, 0x29, 0x52, 0xe9, 0xab, 0x6a,
	0x16, 0xd1, 0x22, 0x97, 0x2b, 0xad, 0xf2, 0x4f, 0xeb, 0x22, 0xcb, 0x79, 0xc4, 0xb2, 0x4c, 0x48,
	0x26, 0xb9, 0xc8, 0x4a, 0x5d, 0x0d, 0x9e, 0x41, 0xff, 0x92, 0xe4, 0xc4, 0x90, 0x63, 0xba, 0xa9,
	0xa8, 0x94, 0x78, 0x04, 0x2e, 0x4f, 0x3c, 0x67, 0xe8, 0x8c, 0x3a, 0xb1, 0xcb, 0x13, 0x1c, 0x40,
	0x5b, 0x52, 0xc6, 0x32, 0xe9, 0xb9, 0x2a, 0x57, 0x47, 0xc1, 0x5b, 0x18, 0xbc, 0x2c, 0x88, 0x49,
	0xda, 0x21, 0x3c, 0x82, 0x8e, 0xf5, 0xab, 0x40, 0xdd, 0x31, 0x86, 0xb5, 0xe1, 0x70, 0xa3, 0xde,
	0x88, 0x82, 0xe7, 0x30, 0x78, 0x45, 0x29, 0x35, 0xb0, 0x6e, 0xeb, 0xe6, 0x33, 0x74, 0x6c, 0xef,
	0x4e, 0x93, 0x0f, 0x87, 0xd3, 0xaa, 0x28, 0x28, 0x9b, 0xae, 0xea, 0x36, 0x1b, 0x63, 0xb4, 0x36,
	0x5b, 0x72, 0x75, 0x30, 0x5e, 0x6b, 0xd8, 0x1a, 0x75, 0xc7, 0x77, 0xb7, 0xcc, 0xea, 0x4a, 0xbc,
	0xd1, 0x04, 0xbf, 0x1c, 0x38, 0x34, 0xf9, 0x9d, 0x49, 0x1e, 0x1c, 0xb0, 0xb2, 0x24, 0xf9, 0x26,
	0xa9, 0x07, 0x99, 0x10, 0xcf, 0xa1, 0xcb, 0x13, 0xca, 0x24, 0x9f, 0x71, 0x2a, 0xcc, 0x24, 0xcf,
	0x4e, 0x7a, 0xa1, 0x65, 0x46, 0x10, 0x6f, 0x8b, 0x71, 0x08, 0xdd, 0x05, 0x2b, 0xae, 0x49, 0x7e,
	0x64, 0x69, 0x45, 0xde, 0xde, 0xd0, 0x19, 0x39, 0xf1, 0x76, 0x6a, 0xfd, 0x87, 0x37, 0x15, 0xcb,
	0x24, 0x97, 0x2b, 0x6f, 0x5f, 0x95, 0x6d, 0x1c, 0x3c, 0x85, 0xde, 0x7f, 0x74, 0x44, 0xd8, 0xbb,
	0xe6, 0x99, 0x31, 0xae, 0xbe, 0xf1, 0x18, 0xf6, 0x97, 0x0a, 0xaf, 0x8d, 0xeb, 0x60, 0xfc, 0xd3,
	0x85, 0x3b, 0xf6, 0x60, 0xdf, 0x53, 0xb1, 0xe4, 0x53, 0xc2, 0x0f, 0xd0, 0xba, 0x24, 0x89, 0xa7,
	0xd6, 0x7d, 0xc3, 0x1e, 0xf9, 0x0d, 0x57, 0x1e, 0x9c, 0x7c, 0xff, 0xfd, 0xe7, 0x87, 0x7b, 0x0f,
	0xfb, 0xd1, 0xf2, 0x71, 0x64, 0xaf, 0xbf, 0x8c, 0xbe, 0xf2, 0xe4, 0x1b, 0xbe, 0x83, 0xb6, 0x5e,
	0x28, 0x6c, 0x68, 0x6d, 0xc4, 0xdd, 0x57, 0xb8, 0x7e, 0x70, 0xf4, 0x2f, 0xee, 0xdc, 0x39, 0xc3,
	0x4f, 0xd0, 0xd6, 0x1b, 0x85, 0x0f, 0x6c, 0x63, 0xf3, 0x8a, 0xf9, 0x83, 0x50, 0x3f, 0x93, 0xd0,
	0xbc, 0xa1, 0xf0, 0xf5, 0xfa, 0x0d, 0x19, 0xb3, 0x67, 0x4d, 0x66, 0x2f, 0x1e, 0xc2, 0x31, 0x17,
	0xe1, 0x82, 0xcd, 0x59, 0x9a, 0xf0, 0x05, 0x33, 0x33, 0x2e, 0x7a, 0x16, 0x5f, 0x4e, 0xd6, 0xb8,
	0x89, 0x73, 0xd5, 0x56, 0xdc, 0x27, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x78, 0x2c, 0x1f, 0x14,
	0xc5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	Get(ctx context.Context, in *GetPortfolioRequest, opts ...grpc.CallOption) (*Portfolio, error)
	Create(ctx context.Context, in *Portfolio, opts ...grpc.CallOption) (*Portfolio, error)
	Delete(ctx context.Context, in *DeletePortfolioRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type portfolioServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortfolioServiceClient(cc *grpc.ClientConn) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) Get(ctx context.Context, in *GetPortfolioRequest, opts ...grpc.CallOption) (*Portfolio, error) {
	out := new(Portfolio)
	err := c.cc.Invoke(ctx, "/aw.apis.PortfolioService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) Create(ctx context.Context, in *Portfolio, opts ...grpc.CallOption) (*Portfolio, error) {
	out := new(Portfolio)
	err := c.cc.Invoke(ctx, "/aw.apis.PortfolioService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) Delete(ctx context.Context, in *DeletePortfolioRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/aw.apis.PortfolioService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
type PortfolioServiceServer interface {
	Get(context.Context, *GetPortfolioRequest) (*Portfolio, error)
	Create(context.Context, *Portfolio) (*Portfolio, error)
	Delete(context.Context, *DeletePortfolioRequest) (*empty.Empty, error)
}

// UnimplementedPortfolioServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPortfolioServiceServer struct {
}

func (*UnimplementedPortfolioServiceServer) Get(ctx context.Context, req *GetPortfolioRequest) (*Portfolio, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedPortfolioServiceServer) Create(ctx context.Context, req *Portfolio) (*Portfolio, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedPortfolioServiceServer) Delete(ctx context.Context, req *DeletePortfolioRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterPortfolioServiceServer(s *grpc.Server, srv PortfolioServiceServer) {
	s.RegisterService(&_PortfolioService_serviceDesc, srv)
}

func _PortfolioService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aw.apis.PortfolioService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).Get(ctx, req.(*GetPortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Portfolio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aw.apis.PortfolioService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).Create(ctx, req.(*Portfolio))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aw.apis.PortfolioService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).Delete(ctx, req.(*DeletePortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortfolioService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aw.apis.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _PortfolioService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PortfolioService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PortfolioService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portfolio.proto",
}
