// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.magaldima.api;

/**
 * Protobuf type {@code api.CreatePortfolioRequest}
 */
public  final class CreatePortfolioRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.CreatePortfolioRequest)
    CreatePortfolioRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreatePortfolioRequest.newBuilder() to construct.
  private CreatePortfolioRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreatePortfolioRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreatePortfolioRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.magaldima.api.Portfolio.Builder subBuilder = null;
            if (portfolio_ != null) {
              subBuilder = portfolio_.toBuilder();
            }
            portfolio_ = input.readMessage(io.magaldima.api.Portfolio.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(portfolio_);
              portfolio_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.magaldima.api.PortfoliosProto.internal_static_api_CreatePortfolioRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.magaldima.api.PortfoliosProto.internal_static_api_CreatePortfolioRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.magaldima.api.CreatePortfolioRequest.class, io.magaldima.api.CreatePortfolioRequest.Builder.class);
  }

  public static final int PORTFOLIO_FIELD_NUMBER = 1;
  private io.magaldima.api.Portfolio portfolio_;
  /**
   * <code>.api.Portfolio portfolio = 1;</code>
   */
  public boolean hasPortfolio() {
    return portfolio_ != null;
  }
  /**
   * <code>.api.Portfolio portfolio = 1;</code>
   */
  public io.magaldima.api.Portfolio getPortfolio() {
    return portfolio_ == null ? io.magaldima.api.Portfolio.getDefaultInstance() : portfolio_;
  }
  /**
   * <code>.api.Portfolio portfolio = 1;</code>
   */
  public io.magaldima.api.PortfolioOrBuilder getPortfolioOrBuilder() {
    return getPortfolio();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (portfolio_ != null) {
      output.writeMessage(1, getPortfolio());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (portfolio_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPortfolio());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.magaldima.api.CreatePortfolioRequest)) {
      return super.equals(obj);
    }
    io.magaldima.api.CreatePortfolioRequest other = (io.magaldima.api.CreatePortfolioRequest) obj;

    boolean result = true;
    result = result && (hasPortfolio() == other.hasPortfolio());
    if (hasPortfolio()) {
      result = result && getPortfolio()
          .equals(other.getPortfolio());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPortfolio()) {
      hash = (37 * hash) + PORTFOLIO_FIELD_NUMBER;
      hash = (53 * hash) + getPortfolio().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.magaldima.api.CreatePortfolioRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.magaldima.api.CreatePortfolioRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.magaldima.api.CreatePortfolioRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.CreatePortfolioRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.CreatePortfolioRequest)
      io.magaldima.api.CreatePortfolioRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.magaldima.api.PortfoliosProto.internal_static_api_CreatePortfolioRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.magaldima.api.PortfoliosProto.internal_static_api_CreatePortfolioRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.magaldima.api.CreatePortfolioRequest.class, io.magaldima.api.CreatePortfolioRequest.Builder.class);
    }

    // Construct using io.magaldima.api.CreatePortfolioRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (portfolioBuilder_ == null) {
        portfolio_ = null;
      } else {
        portfolio_ = null;
        portfolioBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.magaldima.api.PortfoliosProto.internal_static_api_CreatePortfolioRequest_descriptor;
    }

    public io.magaldima.api.CreatePortfolioRequest getDefaultInstanceForType() {
      return io.magaldima.api.CreatePortfolioRequest.getDefaultInstance();
    }

    public io.magaldima.api.CreatePortfolioRequest build() {
      io.magaldima.api.CreatePortfolioRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.magaldima.api.CreatePortfolioRequest buildPartial() {
      io.magaldima.api.CreatePortfolioRequest result = new io.magaldima.api.CreatePortfolioRequest(this);
      if (portfolioBuilder_ == null) {
        result.portfolio_ = portfolio_;
      } else {
        result.portfolio_ = portfolioBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.magaldima.api.CreatePortfolioRequest) {
        return mergeFrom((io.magaldima.api.CreatePortfolioRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.magaldima.api.CreatePortfolioRequest other) {
      if (other == io.magaldima.api.CreatePortfolioRequest.getDefaultInstance()) return this;
      if (other.hasPortfolio()) {
        mergePortfolio(other.getPortfolio());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.magaldima.api.CreatePortfolioRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.magaldima.api.CreatePortfolioRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.magaldima.api.Portfolio portfolio_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.magaldima.api.Portfolio, io.magaldima.api.Portfolio.Builder, io.magaldima.api.PortfolioOrBuilder> portfolioBuilder_;
    /**
     * <code>.api.Portfolio portfolio = 1;</code>
     */
    public boolean hasPortfolio() {
      return portfolioBuilder_ != null || portfolio_ != null;
    }
    /**
     * <code>.api.Portfolio portfolio = 1;</code>
     */
    public io.magaldima.api.Portfolio getPortfolio() {
      if (portfolioBuilder_ == null) {
        return portfolio_ == null ? io.magaldima.api.Portfolio.getDefaultInstance() : portfolio_;
      } else {
        return portfolioBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.Portfolio portfolio = 1;</code>
     */
    public Builder setPortfolio(io.magaldima.api.Portfolio value) {
      if (portfolioBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        portfolio_ = value;
        onChanged();
      } else {
        portfolioBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.api.Portfolio portfolio = 1;</code>
     */
    public Builder setPortfolio(
        io.magaldima.api.Portfolio.Builder builderForValue) {
      if (portfolioBuilder_ == null) {
        portfolio_ = builderForValue.build();
        onChanged();
      } else {
        portfolioBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.api.Portfolio portfolio = 1;</code>
     */
    public Builder mergePortfolio(io.magaldima.api.Portfolio value) {
      if (portfolioBuilder_ == null) {
        if (portfolio_ != null) {
          portfolio_ =
            io.magaldima.api.Portfolio.newBuilder(portfolio_).mergeFrom(value).buildPartial();
        } else {
          portfolio_ = value;
        }
        onChanged();
      } else {
        portfolioBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.api.Portfolio portfolio = 1;</code>
     */
    public Builder clearPortfolio() {
      if (portfolioBuilder_ == null) {
        portfolio_ = null;
        onChanged();
      } else {
        portfolio_ = null;
        portfolioBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.api.Portfolio portfolio = 1;</code>
     */
    public io.magaldima.api.Portfolio.Builder getPortfolioBuilder() {
      
      onChanged();
      return getPortfolioFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.Portfolio portfolio = 1;</code>
     */
    public io.magaldima.api.PortfolioOrBuilder getPortfolioOrBuilder() {
      if (portfolioBuilder_ != null) {
        return portfolioBuilder_.getMessageOrBuilder();
      } else {
        return portfolio_ == null ?
            io.magaldima.api.Portfolio.getDefaultInstance() : portfolio_;
      }
    }
    /**
     * <code>.api.Portfolio portfolio = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.magaldima.api.Portfolio, io.magaldima.api.Portfolio.Builder, io.magaldima.api.PortfolioOrBuilder> 
        getPortfolioFieldBuilder() {
      if (portfolioBuilder_ == null) {
        portfolioBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.magaldima.api.Portfolio, io.magaldima.api.Portfolio.Builder, io.magaldima.api.PortfolioOrBuilder>(
                getPortfolio(),
                getParentForChildren(),
                isClean());
        portfolio_ = null;
      }
      return portfolioBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.CreatePortfolioRequest)
  }

  // @@protoc_insertion_point(class_scope:api.CreatePortfolioRequest)
  private static final io.magaldima.api.CreatePortfolioRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.magaldima.api.CreatePortfolioRequest();
  }

  public static io.magaldima.api.CreatePortfolioRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreatePortfolioRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreatePortfolioRequest>() {
    public CreatePortfolioRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreatePortfolioRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreatePortfolioRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreatePortfolioRequest> getParserForType() {
    return PARSER;
  }

  public io.magaldima.api.CreatePortfolioRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

