// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.magaldima.api;

public interface CreatePortfolioRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.CreatePortfolioRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Portfolio portfolio = 1;</code>
   */
  boolean hasPortfolio();
  /**
   * <code>.api.Portfolio portfolio = 1;</code>
   */
  io.magaldima.api.Portfolio getPortfolio();
  /**
   * <code>.api.Portfolio portfolio = 1;</code>
   */
  io.magaldima.api.PortfolioOrBuilder getPortfolioOrBuilder();
}
