// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.magaldima.api;

public interface DeletePortfolioRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DeletePortfolioRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string tenant = 2;</code>
   */
  java.lang.String getTenant();
  /**
   * <code>string tenant = 2;</code>
   */
  com.google.protobuf.ByteString
      getTenantBytes();
}
