// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.magaldima.api;

public interface GetPortfolioRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.GetPortfolioRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * this field is mapped to the path pattern
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * this field is mapped to the path pattern
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * this field is not mapped to path so is optional is query param
   * </pre>
   *
   * <code>string tenant = 2;</code>
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * this field is not mapped to path so is optional is query param
   * </pre>
   *
   * <code>string tenant = 2;</code>
   */
  com.google.protobuf.ByteString
      getTenantBytes();
}
