// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package io.magaldima.api;

public final class PortfoliosProto {
  private PortfoliosProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_GetPortfolioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_GetPortfolioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_CreatePortfolioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_CreatePortfolioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_DeletePortfolioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_DeletePortfolioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Portfolio_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Portfolio_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Position_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_AssetIdentifier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_AssetIdentifier_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017portfolio.proto\022\003api\032\033google/protobuf/" +
      "empty.proto\032\034google/api/annotations.prot" +
      "o\"1\n\023GetPortfolioRequest\022\n\n\002id\030\001 \001(\t\022\016\n\006" +
      "tenant\030\002 \001(\t\";\n\026CreatePortfolioRequest\022!" +
      "\n\tportfolio\030\001 \001(\0132\016.api.Portfolio\"4\n\026Del" +
      "etePortfolioRequest\022\n\n\002id\030\001 \001(\t\022\016\n\006tenan" +
      "t\030\002 \001(\t\"K\n\tPortfolio\022\n\n\002id\030\001 \001(\t\022\020\n\010curr" +
      "ency\030\002 \001(\t\022 \n\tpositions\030\003 \003(\0132\r.api.Posi" +
      "tion\"y\n\010Position\022\n\n\002id\030\001 \001(\t\022\017\n\007assetId\030" +
      "\002 \001(\t\022)\n\013identifiers\030\003 \003(\0132\024.api.AssetId" +
      "entifier\022\023\n\013marketValue\030\004 \001(\001\022\020\n\010quantit" +
      "y\030\005 \001(\001\".\n\017AssetIdentifier\022\014\n\004kind\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t2\201\002\n\020PortfolioService\022L\n\003" +
      "Get\022\030.api.GetPortfolioRequest\032\016.api.Port" +
      "folio\"\033\202\323\344\223\002\025\022\023/v1/portfolios/{id}\022C\n\006Cr" +
      "eate\022\016.api.Portfolio\032\016.api.Portfolio\"\031\202\323" +
      "\344\223\002\023\"\016/v1/portfolios:\001*\022Z\n\006Delete\022\033.api." +
      "DeletePortfolioRequest\032\026.google.protobuf" +
      ".Empty\"\033\202\323\344\223\002\025*\023/v1/portfolios/{id}B%\n\020i" +
      "o.magaldima.apiB\017PortfoliosProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_api_GetPortfolioRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_GetPortfolioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_GetPortfolioRequest_descriptor,
        new java.lang.String[] { "Id", "Tenant", });
    internal_static_api_CreatePortfolioRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_CreatePortfolioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_CreatePortfolioRequest_descriptor,
        new java.lang.String[] { "Portfolio", });
    internal_static_api_DeletePortfolioRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_DeletePortfolioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_DeletePortfolioRequest_descriptor,
        new java.lang.String[] { "Id", "Tenant", });
    internal_static_api_Portfolio_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_Portfolio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Portfolio_descriptor,
        new java.lang.String[] { "Id", "Currency", "Positions", });
    internal_static_api_Position_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_api_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Position_descriptor,
        new java.lang.String[] { "Id", "AssetId", "Identifiers", "MarketValue", "Quantity", });
    internal_static_api_AssetIdentifier_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_api_AssetIdentifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_AssetIdentifier_descriptor,
        new java.lang.String[] { "Kind", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
